### ISSUE TITLE
Loadout Selector cannot make profiles for Deadlock.

### ISSUE THREAD

**Issue by Sw1ftSN** [DerArkeN/valorant_loadouts#1]
I assume this is because of the new agent's release. Not sure how easy a fix this is. But as of now, creating a profile under the name "deadlock" does not activate upon selecting the agent in games, nor does it show up as a profile in the list.

**Comment by truearken** [comment]
Hello,
try to manually create a file called "deadlock.json" and save it into the "loadouts" folder from the program. then restart the app and try again.
